language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
before_script:
  - npm install -g gulp
script:
  - gulp
  - npm run lint
  - npm run flow
  - npm run test
  - npm run codecov
