language: node_js
node_js:
  - "7"
cache:
  directories:
    - node_modules
before_script:
  - npm install -g yarn
script:
  - yarn install
  - yarn run build
  - yarn run lint
  - yarn run flow
  - yarn run test
  - yarn run codecov
